-- APHOTECH SOLAR ADMIN SETUP
-- Run this after profiles.sql and quote_requests.sql.
-- Safe to run more than once.

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'customer';

UPDATE public.profiles
SET role = 'customer'
WHERE role IS NULL;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin() FROM public;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

ALTER TABLE public.quote_requests
ADD COLUMN IF NOT EXISTS quoted_amount numeric(14,2),
ADD COLUMN IF NOT EXISTS admin_notes text;

DROP POLICY IF EXISTS "Users can update own quote requests" ON public.quote_requests;

DROP POLICY IF EXISTS "Admins can view all quote requests" ON public.quote_requests;
CREATE POLICY "Admins can view all quote requests"
ON public.quote_requests FOR SELECT
TO authenticated
USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can update all quote requests" ON public.quote_requests;
CREATE POLICY "Admins can update all quote requests"
ON public.quote_requests FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  category text NOT NULL CHECK (category IN ('package','appliance')),
  price numeric(14,2),
  description text,
  image_path text,
  badge text,
  capacity text,
  meta_text text,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view active products" ON public.products;
CREATE POLICY "Anyone can view active products"
ON public.products FOR SELECT
TO anon, authenticated
USING (active = true);

DROP POLICY IF EXISTS "Admins can view all products" ON public.products;
CREATE POLICY "Admins can view all products"
ON public.products FOR SELECT
TO authenticated
USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can insert products" ON public.products;
CREATE POLICY "Admins can insert products"
ON public.products FOR INSERT
TO authenticated
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can update products" ON public.products;
CREATE POLICY "Admins can update products"
ON public.products FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can delete products" ON public.products;
CREATE POLICY "Admins can delete products"
ON public.products FOR DELETE
TO authenticated
USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.set_product_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS products_set_updated_at ON public.products;
CREATE TRIGGER products_set_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.set_product_updated_at();

INSERT INTO public.products
(name, category, price, description, image_path, badge, capacity, meta_text, active, sort_order)
VALUES
('1kVA Solar System','package',850000,'Lights, TV, Decoder & Fans','assets/images/1kva.jpg','Popular','1kVA','Nigeria',true,10),
('2kVA Solar System','package',1600000,'TV, Fridge, Fans & Lighting','assets/images/2kva.jpg','Popular','2kVA','Nigeria',true,20),
('3kVA Solar System','package',2500000,'Fridge, Freezer, TVs & Fans','assets/images/3kva.jpg','Best Seller','3kVA','Nigeria',true,30),
('5kVA Solar System','package',4500000,'1HP AC, Pumps & Office Use','assets/images/5kva.jpg','Premium','5kVA','Nigeria',true,40),
('10kVA Solar System','package',8000000,'Multiple ACs, Offices & Commercial','assets/images/10kva.jpg','Commercial','10kVA','Nigeria',true,50),
('Custom / 20kVA+','package',NULL,'Factories, Schools & Estates','assets/images/custom.jpg','Custom','20kVA+','Nigeria',true,60),
('Solar Freezer','appliance',398000,'Energy-efficient solar freezer suitable for homes, shops and small businesses.','assets/images/solar-freezer.jpg','Popular',NULL,'Freezing - Solar Powered',true,10),
('Solar Fan','appliance',85000,'Efficient solar-powered fan designed to provide comfortable cooling with low energy consumption.','assets/images/solar-fan.jpg','Energy Saver',NULL,'Cooling - Solar Powered',true,20),
('Solar Iron','appliance',29000,'Low-power solar iron designed for efficient everyday home use.','assets/images/solar-iron.jpg','New',NULL,'Home Use - Low Power',true,30)
ON CONFLICT (name) DO UPDATE SET
  category=EXCLUDED.category,
  description=EXCLUDED.description,
  image_path=EXCLUDED.image_path,
  badge=EXCLUDED.badge,
  capacity=EXCLUDED.capacity,
  meta_text=EXCLUDED.meta_text,
  active=EXCLUDED.active,
  sort_order=EXCLUDED.sort_order;

UPDATE public.profiles
SET role='admin', updated_at=now()
WHERE lower(email) IN ('oloyedeafo1997@gmail.com','aphotechsolar@gmail.com');

SELECT id,email,role
FROM public.profiles
WHERE lower(email) IN ('oloyedeafo1997@gmail.com','aphotechsolar@gmail.com')
ORDER BY email;
