-- =====================================================
-- APHOTECH SOLAR SOLUTION
-- ADMIN REQUEST MANAGEMENT + EDITABLE PRICES
-- Run this AFTER quote_requests.sql and profiles.sql.
-- =====================================================

-- 1) Add a secure role to customer profiles.
alter table public.profiles
  add column if not exists role text not null default 'customer';

-- Keep roles limited to known values.
update public.profiles set role = 'customer' where role is null;

-- 2) Helper used by RLS. SECURITY DEFINER avoids recursive profile policies.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- 3) Quote administration fields.
alter table public.quote_requests
  add column if not exists quoted_amount numeric(14,2),
  add column if not exists admin_notes text;

-- Customers should not be able to change quote status/amount/notes.
drop policy if exists "Users can update own quote requests" on public.quote_requests;

-- Admins can see every request.
drop policy if exists "Admins can view all quote requests" on public.quote_requests;
create policy "Admins can view all quote requests"
on public.quote_requests for select
to authenticated
using (public.is_admin());

-- Admins can update status, amount and notes.
drop policy if exists "Admins can update all quote requests" on public.quote_requests;
create policy "Admins can update all quote requests"
on public.quote_requests for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- 4) Editable products/packages.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null check (category in ('package','appliance')),
  price numeric(14,2),
  description text,
  image_path text,
  badge text,
  capacity text,
  meta_text text,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Public/authenticated customers can only read active products.
drop policy if exists "Anyone can view active products" on public.products;
create policy "Anyone can view active products"
on public.products for select
to anon, authenticated
using (active = true);

-- Admins can manage all products.
drop policy if exists "Admins can view all products" on public.products;
create policy "Admins can view all products"
on public.products for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products for delete
to authenticated
using (public.is_admin());

create or replace function public.set_product_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute procedure public.set_product_updated_at();

-- 5) Seed the current website prices. Existing rows are updated by name.
insert into public.products (name, category, price, description, image_path, badge, capacity, meta_text, active, sort_order)
values
  ('1kVA Solar System', 'package', 850000, 'Lights, TV, Decoder & Fans', 'assets/images/1kva.jpg', 'Popular', '1kVA', 'Nigeria', true, 10),
  ('2kVA Solar System', 'package', 1600000, 'TV, Fridge, Fans & Lighting', 'assets/images/2kva.jpg', 'Popular', '2kVA', 'Nigeria', true, 20),
  ('3kVA Solar System', 'package', 2500000, 'Fridge, Freezer, TVs & Fans', 'assets/images/3kva.jpg', 'Best Seller', '3kVA', 'Nigeria', true, 30),
  ('5kVA Solar System', 'package', 4500000, '1HP AC, Pumps & Office Use', 'assets/images/5kva.jpg', 'Premium', '5kVA', 'Nigeria', true, 40),
  ('10kVA Solar System', 'package', 8000000, 'Multiple ACs, Offices & Commercial', 'assets/images/10kva.jpg', 'Commercial', '10kVA', 'Nigeria', true, 50),
  ('Custom / 20kVA+', 'package', null, 'Factories, Schools & Estates', 'assets/images/custom.jpg', 'Custom', '20kVA+', 'Nigeria', true, 60),
  ('Solar Freezer', 'appliance', 398000, 'Energy-efficient solar freezer suitable for homes, shops and small businesses.', 'assets/images/solar-freezer.jpg', 'Popular', null, 'Freezing • Solar Powered', true, 10),
  ('Solar Fan', 'appliance', 85000, 'Efficient solar-powered fan designed to provide comfortable cooling with low energy consumption.', 'assets/images/solar-fan.jpg', 'Energy Saver', null, 'Cooling • Solar Powered', true, 20),
  ('Solar Iron', 'appliance', 29000, 'Low-power solar iron designed for efficient everyday home use.', 'assets/images/solar-iron.jpg', 'New', null, 'Home Use • Low Power', true, 30)
on conflict (name) do update set
  category = excluded.category,
  description = excluded.description,
  image_path = excluded.image_path,
  badge = excluded.badge,
  capacity = excluded.capacity,
  meta_text = excluded.meta_text,
  sort_order = excluded.sort_order;

-- IMPORTANT: replace this example email with the email you use to log in.
-- update public.profiles set role = 'admin' where email = 'YOUR-ADMIN-EMAIL@example.com';
