-- APHOTECH SOLAR PROJECT MEDIA MANAGEMENT
-- Run this once in Supabase SQL Editor after the existing admin setup.

CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  location text,
  description text,
  media_type text NOT NULL CHECK (media_type IN ('image','video')),
  media_url text NOT NULL,
  thumbnail_url text,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view active projects" ON public.projects;
CREATE POLICY "Anyone can view active projects"
ON public.projects FOR SELECT
TO anon, authenticated
USING (active = true);

DROP POLICY IF EXISTS "Admins can view all projects" ON public.projects;
CREATE POLICY "Admins can view all projects"
ON public.projects FOR SELECT
TO authenticated
USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can insert projects" ON public.projects;
CREATE POLICY "Admins can insert projects"
ON public.projects FOR INSERT
TO authenticated
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can update projects" ON public.projects;
CREATE POLICY "Admins can update projects"
ON public.projects FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can delete projects" ON public.projects;
CREATE POLICY "Admins can delete projects"
ON public.projects FOR DELETE
TO authenticated
USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.set_project_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS projects_set_updated_at ON public.projects;
CREATE TRIGGER projects_set_updated_at
BEFORE UPDATE ON public.projects
FOR EACH ROW EXECUTE FUNCTION public.set_project_updated_at();

INSERT INTO storage.buckets (id, name, public)
VALUES ('project-media', 'project-media', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Admins can upload project media" ON storage.objects;
CREATE POLICY "Admins can upload project media"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'project-media' AND public.is_admin());

DROP POLICY IF EXISTS "Admins can update project media" ON storage.objects;
CREATE POLICY "Admins can update project media"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'project-media' AND public.is_admin())
WITH CHECK (bucket_id = 'project-media' AND public.is_admin());

DROP POLICY IF EXISTS "Admins can delete project media" ON storage.objects;
CREATE POLICY "Admins can delete project media"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'project-media' AND public.is_admin());

DROP POLICY IF EXISTS "Anyone can view project media" ON storage.objects;
CREATE POLICY "Anyone can view project media"
ON storage.objects FOR SELECT
TO anon, authenticated
USING (bucket_id = 'project-media');
