-- =====================================================
-- APHOTECH SOLAR SOLUTION
-- CUSTOMER QUOTE REQUESTS
-- Run this once in Supabase SQL Editor.
-- =====================================================

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  phone text not null,
  email text,
  location text not null,
  property_type text not null,
  preferred_package text,
  loads text[] not null default '{}',
  message text,
  status text not null default 'Pending'
    check (status in ('Pending','Reviewed','Quoted','Completed','Cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.quote_requests enable row level security;

drop policy if exists "Users can view own quote requests" on public.quote_requests;
create policy "Users can view own quote requests"
on public.quote_requests for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own quote requests" on public.quote_requests;
create policy "Users can create own quote requests"
on public.quote_requests for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own quote requests" on public.quote_requests;
create policy "Users can update own quote requests"
on public.quote_requests for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create or replace function public.set_quote_request_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists quote_requests_set_updated_at on public.quote_requests;
create trigger quote_requests_set_updated_at
before update on public.quote_requests
for each row execute procedure public.set_quote_request_updated_at();

create index if not exists quote_requests_user_id_created_at_idx
on public.quote_requests (user_id, created_at desc);
